### PR TITLE
test-cases: Run Example tests

### PR DESCRIPTION
**Pull request by rbradford**
If there are Example...() tests defined run them in test-cases.

Fixes: #1379

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@markdryan good bug!

**Comment by rbradford** [comment]
@markdryan thoughts on what to do? go test won't run those tests due to the requirements you told me about today (e.g. the comment.)

**Comment by markdryan** [comment]
Yeah, I saw this.  We'd need to look at the go test code to figure out how it decides not to run them.  Or we could do a hack an ignore NOT RUN errors for examples.

**Comment by rbradford** [comment]
@markdryan I addressed this by using the go/doc package as a per go test.

**Pull request merged**
